name:  code_structure_linux


on:
  push:
    branches: 
      - dev
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1



    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/requirements.txt') }}



   
    - name: Set up Python 3.6.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.*




      
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      

      
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
   



          

    - name: Install numpy
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: pip install numpy
      
    - name: Install repo
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: pip install -e . -r requirements.txt


    - name: repo path
      run: python -c "import mlmodels,os ; print(mlmodels); print(os)"


    ########  Test running 
    - name: ml_test
      run: ml_test
      
         



# https://ianwhitestone.work/AWS-Serverless-Deployments-With-Github-Actions/
#
#
#
#
