name:  test

on:
  push:
    branches: 
      - dev


 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1


   
    - name: Set up Python 3.6.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.*




    - name: ml_test
      run:  python -c "import os; print(os)"     2>&1 | tee -a log_$(date '+%Y-%m-%d_%H:%M:%S,%3N').txt
      
         
